# 1. Información del Taller
site_name: Tiras y matrices de LEDs
site_description: Repositorio con web dedicado a dar unas notas sobre algunos de estos elementos. El tema será tratado tanto desde el entorno gráfico de ArduinoBlocks como desde el IDE de Arduino.
site_author: Federico Coca
site_url: https://fgcoca.github.io/tiras-y-matrices-de-LEDs/

# 2. Repositorio
repo_name: fgcoca/tiras-y-matrices-de-LEDs
repo_url: https://github.com/fgcoca/tiras-y-matrices-de-LEDs
edit_uri: ""

# 3. Copyright
copyright: Copyright &copy; 2020 - 2035 Federico Coca

# 4. RRSS
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/fgcoca
      name: Twitter de Federico Coca
    - icon: fontawesome/brands/github
      link: https://github.com/fgcoca
      name: Github de Federico Coca
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cocafederico/?hl=es
      name: Instagram de Federico Coca
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clubroboticagra
      name: Twitter de Club Robótica Granada 

# 5. Navegación
nav:
  - Introducción: index.md
  - Software: 
    - ArduinoBlocks: temas/softAB.md
    - IDE 2: temas/softIDE.md
  - Alimentación: temas/alimentar.md
  - Programación:
    - Matriz WS2812 8x32: temas/matriz8x32.md
    - Matriz WS2812 16x16: temas/matriz16x16.md
    - Matriz WS2812 8x8: temas/matriz8x8.md
    - Matrices de 8x8 LEDs: temas/LED8x8.md
  - El juego de la serpiente:
    - 3D: temas/3d.md
    - Programa: temas/serpiente.md
  - Miscelanea:
    - Autor: Miscelanea/about.md 
    - Licencias: Miscelanea/lic.md
    - Webgrafia/Bibliografía: Miscelanea/webgrafia.md
    - Software utilizado: Miscelanea/soft.md

# 6. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 7. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    primary: light blue
    accent: deep purple 
  font:
    text: Roboto 
    code: Roboto Mono 
  logo: img/favicon.png 
  favicon: img/favicon.png 
  language: es
  extra:
    search:
      language: es, en
  # Página 404
  static_templates:
    - 404.html
  # No incluir los JavaScript de MkDocs
  #include_search_page: false
  #search_index_only: true

# 8. Extensiones
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      # guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 9. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  # Este fichero es opcional y solo si se quiere sobreescribir la configuracion del plugin
  #- js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# 10. Plugins
plugins:
  - search
  - minify:
      minify_html: true
